### ISSUE TITLE
Set restrictions in the frontend so that the ships can be either vertical or horizontal with inputs.

### ISSUE THREAD

**Issue by Nickschlaedde** [sopra-fs23-group-11/sopra-fs23-group-11-client#45]

**Comment by qing-dai** [comment]
https://github.com/sopra-fs23-group-11/sopra-fs23-group-11-client/commit/7cc6e640ee973e093fa07f80ac4e99b2fe38ebee

**Comment by qing-dai** [comment]
https://github.com/sopra-fs23-group-11/sopra-fs23-group-11-client/commit/0c718a6f881db54cdd9ddb02d72d2028b9111ec4
